import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from '../../lib/wrappers/provider'
import Header from '@/components/base/header'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-gray-50 ${inter.className}`}>
        <Provider>
        <Header/>
          <div className='max-w-[80%] m-auto'>
          {children}
          </div>
        </Provider>
        
        
        </body>
    </html>
  )
}
